modules/tree_gardener/src/tree_gardener/tree_factory.py, modules/tree_gardener/src/tree_gardener/tree_parser.py, tree_generator/self_contained_tree.xml, tree_generator/test.xml
=> New decorators

tree_translator/generate_app.py, tree_translator/ros_template/package.xml, tree_translator/ros_template/thirdparty.repos, tree_translator/trees/self_contained_tree.xml
Fixes #22: 
* The app generator now populates the package.xml with all the dependencies in the rosdep
* The app template now includes a handy thirdparty.repos, for optional use if the users want to use the recommended tools.
=> Dependencies manager

backend/tree_api/json_translator.py
This pull request fixes #73.
This sorts the nodes in ascending order.
=> Fixed issue 73

frontend/src/components/diagram_editor/NodeHeader.css, frontend/src/components/diagram_editor/NodeHeader.js, frontend/src/components/file_editor/FileEditor.js
Adding file autosave when changing file or changing project
=> Adding autosave

frontend/src/components/diagram_editor/NodeHeader.css, frontend/src/components/diagram_editor/NodeHeader.js
Updating the css so the buttons are hovered in a correct way
=> Changing css to get the hover state of the icons correctly

backend/filesystem/recepcionist_demo/actions/AskDrink.py, backend/filesystem/recepcionist_demo/actions/AskName.py, backend/filesystem/recepcionist_demo/actions/Greet.py, backend/filesystem/recepcionist_demo/actions/Move.py, backend/filesystem/recepcionist_demo/actions/OrderDrink.py, backend/filesystem/recepcionist_demo/actions/ServeDrink.py, backend/filesystem/recepcionist_demo/actions/SetDestination.py, backend/filesystem/recepcionist_demo/actions/WaitPerson.py, backend/filesystem/recepcionist_demo/graph.json
Adding a new demo with actions.
Maybe it is needed to change what is in #74 because it has the patch already applied.
=> Adding new recepcionist demo

frontend/src/App.css, frontend/src/App.js, frontend/src/components/diagram_editor/DiagramEditor.tsx, frontend/src/components/diagram_editor/modals/EditTagModal.jsx, frontend/src/components/diagram_editor/nodes/tag_node/TagNodeModel.ts, frontend/src/components/error_popup/ErrorModal.css, frontend/src/components/error_popup/ErrorModal.jsx, frontend/src/components/file_editor/FileEditor.js, frontend/src/components/header_menu/HeaderMenu.js, frontend/src/components/header_menu/ProjectModal.jsx
Switched from using window.alert to a custom popup.
=> Added error popup

docs/_pages/documentation.md
=> [gh-pages] Trying another link

.github/workflows/black.yml, .github/workflows/prettier.yml
This adds basic linting for python and js files.
=> Linters pipeline

backend/filesystem/visual_follow_person/code/graph.json, backend/filesystem/visual_follow_person/universes/test_world/config.json, backend/filesystem/visual_follow_person/universes/test_world/universe.launch.py, backend/filesystem/visual_follow_person/universes/test_world/universe.world, frontend/src/App.js, frontend/src/components/diagram_editor/NodeHeader.js, frontend/src/components/header_menu/HeaderMenu.css, frontend/src/components/header_menu/HeaderMenu.js
=> Solving little bugs caused by the merge

.github/workflows/black.yml
Changing workflow in order to fix error on forks
=> Changing workflow in order to fix error on forks

frontend/src/App.js, frontend/src/components/diagram_editor/DiagramEditor.tsx, frontend/src/components/file_browser/FileBrowser.js
Added a prop isDiagramEditor ready to track when the node info array is completely filled.
=> Added state variable to only load de colors when the data is fully filled

frontend/src/App.js, frontend/src/components/diagram_editor/DiagramEditor.tsx, frontend/src/components/diagram_editor/NodeHeader.js, frontend/src/components/file_browser/FileBrowser.js, frontend/src/components/file_editor/FileEditor.js, frontend/src/components/header_menu/HeaderMenu.js, frontend/src/components/header_menu/modals/ProjectModal.jsx, frontend/src/components/header_menu/modals/UniverseModal.jsx, frontend/src/components/header_menu/modals/UniverseUploadModal.jsx, frontend/src/components/settings_popup/SettingsModal.jsx
This improves readability and simplifies promise chains.
=> API calls standarized using async functions and await

frontend/src/components/diagram_editor/nodes/tag_node/TagNodeModel.ts
=> Adding real select handler for tag nodes

frontend/src/App.css, frontend/src/components/Modal/Modal.css, frontend/src/components/diagram_editor/DiagramEditor.tsx, frontend/src/components/diagram_editor/NodeHeader.css, frontend/src/components/diagram_editor/modals/EditActionModal.css, frontend/src/components/diagram_editor/modals/EditActionModal.jsx, frontend/src/components/diagram_editor/nodes/basic_node/BasicNode.css, frontend/src/components/diagram_editor/nodes/basic_node/BasicNodeWidget.tsx, frontend/src/components/diagram_editor/nodes/tag_node/TagNode.css, frontend/src/components/diagram_editor/nodes/tag_node/TagNodeModel.ts, frontend/src/components/diagram_editor/nodes/tag_node/TagNodeWidget.tsx, frontend/src/components/helper/colorHelper.ts, frontend/src/components/settings_popup/options/Checkbox.css
Moving color variables to main css and switching text color depending on action background
=> Moving color variables to main css

frontend/src/components/diagram_editor/DiagramEditor.tsx
=> Hot fix for nodes being bugged

backend/ros_template/ros_template/execute_docker.py, backend/tree_api/json_translator.py, backend/tree_api/urls.py, backend/tree_api/views.py, backend/tree_gardener/tree_gardener/tree_tools.py, frontend/src/App.css, frontend/src/App.tsx, frontend/src/api_helper/CommsManager.ts, frontend/src/api_helper/TreeWrapper.ts, frontend/src/components/bt_status_visualizer/DiagramEditor.css, frontend/src/components/bt_status_visualizer/DiagramVisualizer.tsx, frontend/src/components/bt_status_visualizer/DiagramVisualizerContainer.tsx, frontend/src/components/diagram_editor/DiagramEditor.tsx, frontend/src/components/diagram_editor/NodeMenu.tsx, frontend/src/components/diagram_editor/modals/EditActionModal.jsx, frontend/src/components/diagram_editor/nodes/basic_node/BasicNodeModel.ts, frontend/src/components/diagram_editor/nodes/basic_node/BasicNodeWidget.tsx, frontend/src/components/header_menu/HeaderMenu.tsx, frontend/src/components/header_menu/img/eye_closed.svg, frontend/src/components/header_menu/img/eye_open.svg
Adding BT status visualization
=> Adding BT status visualization

backend/tree_api/views.py, frontend/src/api_helper/TreeWrapper.ts, frontend/src/components/header_menu/HeaderMenu.tsx
=> Adding custom universe back

backend/tree_api/views.py, frontend/src/components/tree_editor/DiagramVisualizer.tsx
=> Create subtree fix

frontend/src/api_helper/TreeWrapper.ts, frontend/src/components/file_browser/file_explorer/MoreActionsMenu.tsx, frontend/src/components/file_browser/file_explorer/TreeNode.tsx
Read only files for trees subfolder
=> Read only files for trees subfolder

frontend/src/App.tsx, frontend/src/api_helper/CommsManager.ts, frontend/src/components/file_browser/modals/NewFileModal.tsx, frontend/src/components/file_editor/FileEditor.css, frontend/src/components/file_editor/FileEditor.tsx
Add more monaco features to match Robotics Academy
=> Add more monaco features

frontend/src/api_helper/TreeWrapper.ts
#274  Getting CSRF token directly from browser using document.cookie solved the issue. It fetched the CSRF token from string containing different cookies.
=> Solution  for csrfToken error

backend/filesystem/visual_follow_person/universes/test_world/universe.launch.py, backend/tree_api/urls.py, backend/tree_api/views.py, frontend/src/api_helper/TreeWrapper.ts, frontend/src/components/file_browser/FileBrowser.tsx, frontend/src/components/header_menu/HeaderMenu.tsx
Fix custom universes launch compressing them in the frontend instead of the backend
=> Fix custom universes launch
